import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HomePage from "./page";
import NavPage from "./Components/SideBar/page";
import FormBox from "./Components/FormBox/page";
import SideBar from "./Components/SideBar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavPage />
        <FormBox />
        <SideBar />
        {children}
      </body>
    </html>
  );
}
