// this file is the blueprint for all pages --> as this layout is in the root of our app
import Header from "@/Components/Header"; // The @ symbol is an abbreviation for ./src/*
import Footer from "@/Components/Footer";
import Nav from "@/Components/Nav";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
