import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavPage from "./Components/header";
import { Montserrat } from "next/font/google";
import Footer from "./Components/footer.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserratFont = Montserrat({
  subsets: ["latin"],
  weight: "500",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserratFont.className}>
        <NavPage />
        <div className="body">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
